source 'https://rubygems.org'

# Specify your gem's dependencies in elasticsearch-model.gemspec
gemspec

if File.exist? File.expand_path("../../../elasticsearch-ruby/elasticsearch-v2", __FILE__)
  gem 'elasticsearch-v2', :path => File.expand_path("../../../elasticsearch-ruby/elasticsearch-v2", __FILE__), :require => false
end

if File.exist? File.expand_path("../../../elasticsearch-ruby/elasticsearch-transport-v2", __FILE__)
  gem 'elasticsearch-transport-v2', :path => File.expand_path("../../../elasticsearch-ruby/elasticsearch-transport-v2", __FILE__), :require => false
end

if File.exist? File.expand_path("../../../elasticsearch-ruby/elasticsearch-api-v2", __FILE__)
  gem 'elasticsearch-api-v2', :path => File.expand_path("../../../elasticsearch-ruby/elasticsearch-api-v2", __FILE__), :require => false
end

if File.exist? File.expand_path("../../../elasticsearch-ruby/elasticsearch-extensions-v2", __FILE__)
  gem 'elasticsearch-extensions-v2', :path => File.expand_path("../../../elasticsearch-ruby/elasticsearch-extensions-v2", __FILE__), :require => false
end
