source 'https://rubygems.org'

# Specify your gem's dependencies in elasticsearch-rails.gemspec
gemspec

# TODO: Figure out how to specify dependency on local elasticsearch-model without endless "Resolving dependencies"
# if File.exists? File.expand_path("../../elasticsearch-model", __FILE__)
#   gem 'elasticsearch-model', :path => File.expand_path("../../elasticsearch-model", __FILE__), :require => true
# end

if File.exist? File.expand_path("../../elasticsearch-model-v2", __FILE__)
  gem 'elasticsearch-model-v2', :path => File.expand_path("../../elasticsearch-model-v2", __FILE__), :require => false
end

if File.exist? File.expand_path("../../../elasticsearch-ruby/elasticsearch-v2", __FILE__)
  gem 'elasticsearch-v2', :path => File.expand_path("../../../elasticsearch-ruby/elasticsearch-v2", __FILE__), :require => false
end

if File.exist? File.expand_path("../../../elasticsearch-ruby/elasticsearch-transport-v2", __FILE__)
  gem 'elasticsearch-transport-v2', :path => File.expand_path("../../../elasticsearch-ruby/elasticsearch-transport-v2", __FILE__), :require => false
end

if File.exist? File.expand_path("../../../elasticsearch-ruby/elasticsearch-api-v2", __FILE__)
  gem 'elasticsearch-api-v2', :path => File.expand_path("../../../elasticsearch-ruby/elasticsearch-api-v2", __FILE__), :require => false
end

if File.exist? File.expand_path("../../../elasticsearch-ruby/elasticsearch-extensions-v2", __FILE__)
  gem 'elasticsearch-extensions-v2', :path => File.expand_path("../../../elasticsearch-ruby/elasticsearch-extensions-v2", __FILE__), :require => false
end
